project:
  type: website
  output-dir: docs

website:
  title: "Faiz Essa"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research

format:
  html:
    theme:
      - cosmo
      - navbar_style.scss
    css: styles.css
    toc: true

editor: visual

