project:
  render:
    - index.qmd
  type: website
  output-dir: docs

website:
  title: "Faiz Essa"
  navbar:
    left:
      - href: index.qmd
        text: About

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

editor: visual

